version: '2'
services:
  artosh-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/Artosh/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Artosh
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
